{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-redis-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
{{- end }}
